//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnturSystray.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnturSystray.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // Window Titles
        public static string SettingsWindow_Title => ResourceManager.GetString("SettingsWindow_Title", resourceCulture) ?? "";
        public static string IconEditDialog_Title => ResourceManager.GetString("IconEditDialog_Title", resourceCulture) ?? "";

        // Common Buttons
        public static string Button_Save => ResourceManager.GetString("Button_Save", resourceCulture) ?? "";
        public static string Button_Cancel => ResourceManager.GetString("Button_Cancel", resourceCulture) ?? "";
        public static string Button_Add => ResourceManager.GetString("Button_Add", resourceCulture) ?? "";
        public static string Button_Edit => ResourceManager.GetString("Button_Edit", resourceCulture) ?? "";
        public static string Button_Remove => ResourceManager.GetString("Button_Remove", resourceCulture) ?? "";
        public static string Button_MoveUp => ResourceManager.GetString("Button_MoveUp", resourceCulture) ?? "";
        public static string Button_MoveDown => ResourceManager.GetString("Button_MoveDown", resourceCulture) ?? "";
        public static string Button_Search => ResourceManager.GetString("Button_Search", resourceCulture) ?? "";
        public static string Button_Weekdays => ResourceManager.GetString("Button_Weekdays", resourceCulture) ?? "";
        public static string Button_Weekends => ResourceManager.GetString("Button_Weekends", resourceCulture) ?? "";
        public static string Button_AllDays => ResourceManager.GetString("Button_AllDays", resourceCulture) ?? "";

        // Settings Window Labels
        public static string Label_TrayIcons => ResourceManager.GetString("Label_TrayIcons", resourceCulture) ?? "";
        public static string Label_RefreshInterval => ResourceManager.GetString("Label_RefreshInterval", resourceCulture) ?? "";
        public static string Label_SecondsMin10 => ResourceManager.GetString("Label_SecondsMin10", resourceCulture) ?? "";
        public static string Label_Language => ResourceManager.GetString("Label_Language", resourceCulture) ?? "";
        public static string Label_MaxIcons => ResourceManager.GetString("Label_MaxIcons", resourceCulture) ?? "";

        // Icon Edit Dialog Labels
        public static string Label_DisplayName => ResourceManager.GetString("Label_DisplayName", resourceCulture) ?? "";
        public static string Label_IconColor => ResourceManager.GetString("Label_IconColor", resourceCulture) ?? "";
        public static string Label_StopSearch => ResourceManager.GetString("Label_StopSearch", resourceCulture) ?? "";
        public static string Label_Stop => ResourceManager.GetString("Label_Stop", resourceCulture) ?? "";
        public static string Label_Quay => ResourceManager.GetString("Label_Quay", resourceCulture) ?? "";
        public static string Label_Line => ResourceManager.GetString("Label_Line", resourceCulture) ?? "";
        public static string Label_Destination => ResourceManager.GetString("Label_Destination", resourceCulture) ?? "";
        public static string Label_Time => ResourceManager.GetString("Label_Time", resourceCulture) ?? "";
        public static string Label_Days => ResourceManager.GetString("Label_Days", resourceCulture) ?? "";
        public static string Checkbox_EnableSchedule => ResourceManager.GetString("Checkbox_EnableSchedule", resourceCulture) ?? "";

        // Day Abbreviations
        public static string Day_Mon => ResourceManager.GetString("Day_Mon", resourceCulture) ?? "";
        public static string Day_Tue => ResourceManager.GetString("Day_Tue", resourceCulture) ?? "";
        public static string Day_Wed => ResourceManager.GetString("Day_Wed", resourceCulture) ?? "";
        public static string Day_Thu => ResourceManager.GetString("Day_Thu", resourceCulture) ?? "";
        public static string Day_Fri => ResourceManager.GetString("Day_Fri", resourceCulture) ?? "";
        public static string Day_Sat => ResourceManager.GetString("Day_Sat", resourceCulture) ?? "";
        public static string Day_Sun => ResourceManager.GetString("Day_Sun", resourceCulture) ?? "";

        // Day Groupings
        public static string Days_Daily => ResourceManager.GetString("Days_Daily", resourceCulture) ?? "";
        public static string Days_MonFri => ResourceManager.GetString("Days_MonFri", resourceCulture) ?? "";
        public static string Days_SatSun => ResourceManager.GetString("Days_SatSun", resourceCulture) ?? "";

        // Dropdown Options
        public static string Option_AllQuays => ResourceManager.GetString("Option_AllQuays", resourceCulture) ?? "";
        public static string Option_AllLines => ResourceManager.GetString("Option_AllLines", resourceCulture) ?? "";
        public static string Option_AllDestinations => ResourceManager.GetString("Option_AllDestinations", resourceCulture) ?? "";

        // Context Menu
        public static string Menu_RefreshNow => ResourceManager.GetString("Menu_RefreshNow", resourceCulture) ?? "";
        public static string Menu_Settings => ResourceManager.GetString("Menu_Settings", resourceCulture) ?? "";
        public static string Menu_Exit => ResourceManager.GetString("Menu_Exit", resourceCulture) ?? "";

        // Tray Tooltips
        public static string Tooltip_NoScheduledDepartures => ResourceManager.GetString("Tooltip_NoScheduledDepartures", resourceCulture) ?? "";
        public static string Tooltip_ClickSettingsToAdd => ResourceManager.GetString("Tooltip_ClickSettingsToAdd", resourceCulture) ?? "";
        public static string Tooltip_Loading => ResourceManager.GetString("Tooltip_Loading", resourceCulture) ?? "";
        public static string Tooltip_NoDepartures => ResourceManager.GetString("Tooltip_NoDepartures", resourceCulture) ?? "";
        public static string Tooltip_NoUpcoming => ResourceManager.GetString("Tooltip_NoUpcoming", resourceCulture) ?? "";
        public static string Tooltip_Realtime => ResourceManager.GetString("Tooltip_Realtime", resourceCulture) ?? "";
        public static string Tooltip_MinFormat => ResourceManager.GetString("Tooltip_MinFormat", resourceCulture) ?? "";

        // Status Messages
        public static string Status_LoadingConfig => ResourceManager.GetString("Status_LoadingConfig", resourceCulture) ?? "";
        public static string Status_Ready => ResourceManager.GetString("Status_Ready", resourceCulture) ?? "";
        public static string Status_Searching => ResourceManager.GetString("Status_Searching", resourceCulture) ?? "";
        public static string Status_NoStopsFound => ResourceManager.GetString("Status_NoStopsFound", resourceCulture) ?? "";
        public static string Status_FoundStops => ResourceManager.GetString("Status_FoundStops", resourceCulture) ?? "";
        public static string Status_LoadingQuays => ResourceManager.GetString("Status_LoadingQuays", resourceCulture) ?? "";
        public static string Status_LoadedQuays => ResourceManager.GetString("Status_LoadedQuays", resourceCulture) ?? "";

        // Error Messages
        public static string Error_MaxIconsAllowed => ResourceManager.GetString("Error_MaxIconsAllowed", resourceCulture) ?? "";
        public static string Error_RefreshIntervalNumber => ResourceManager.GetString("Error_RefreshIntervalNumber", resourceCulture) ?? "";
        public static string Error_RefreshIntervalMin10 => ResourceManager.GetString("Error_RefreshIntervalMin10", resourceCulture) ?? "";
        public static string Error_InvalidStop => ResourceManager.GetString("Error_InvalidStop", resourceCulture) ?? "";
        public static string Error_SaveFailed => ResourceManager.GetString("Error_SaveFailed", resourceCulture) ?? "";
        public static string Error_EnterSearchTerm => ResourceManager.GetString("Error_EnterSearchTerm", resourceCulture) ?? "";
        public static string Error_SearchFailed => ResourceManager.GetString("Error_SearchFailed", resourceCulture) ?? "";
        public static string Error_LoadQuaysFailed => ResourceManager.GetString("Error_LoadQuaysFailed", resourceCulture) ?? "";
        public static string Error_SelectValidStop => ResourceManager.GetString("Error_SelectValidStop", resourceCulture) ?? "";
        public static string Error_InvalidQuayId => ResourceManager.GetString("Error_InvalidQuayId", resourceCulture) ?? "";
        public static string Error_SelectAtLeastOneDay => ResourceManager.GetString("Error_SelectAtLeastOneDay", resourceCulture) ?? "";

        // Default Values
        public static string Default_UnconfiguredIcon => ResourceManager.GetString("Default_UnconfiguredIcon", resourceCulture) ?? "";
        public static string Default_BusDeparture => ResourceManager.GetString("Default_BusDeparture", resourceCulture) ?? "";
        public static string Default_Departures => ResourceManager.GetString("Default_Departures", resourceCulture) ?? "";
        public static string Default_LinePrefix => ResourceManager.GetString("Default_LinePrefix", resourceCulture) ?? "";
        public static string Default_LinesFormat => ResourceManager.GetString("Default_LinesFormat", resourceCulture) ?? "";

        // Color Names
        public static string Color_Yellow => ResourceManager.GetString("Color_Yellow", resourceCulture) ?? "";
        public static string Color_Cyan => ResourceManager.GetString("Color_Cyan", resourceCulture) ?? "";
        public static string Color_Lime => ResourceManager.GetString("Color_Lime", resourceCulture) ?? "";
        public static string Color_Orange => ResourceManager.GetString("Color_Orange", resourceCulture) ?? "";
        public static string Color_Magenta => ResourceManager.GetString("Color_Magenta", resourceCulture) ?? "";
        public static string Color_White => ResourceManager.GetString("Color_White", resourceCulture) ?? "";
        public static string Color_Red => ResourceManager.GetString("Color_Red", resourceCulture) ?? "";
        public static string Color_SkyBlue => ResourceManager.GetString("Color_SkyBlue", resourceCulture) ?? "";

        // Language Names
        public static string Language_Auto => ResourceManager.GetString("Language_Auto", resourceCulture) ?? "";
        public static string Language_English => ResourceManager.GetString("Language_English", resourceCulture) ?? "";
        public static string Language_Norwegian => ResourceManager.GetString("Language_Norwegian", resourceCulture) ?? "";

        // Update Check
        public static string Checkbox_CheckForUpdates => ResourceManager.GetString("Checkbox_CheckForUpdates", resourceCulture) ?? "";
        public static string Update_Available => ResourceManager.GetString("Update_Available", resourceCulture) ?? "";
        public static string Update_Download => ResourceManager.GetString("Update_Download", resourceCulture) ?? "";
    }
}
